name: Dynamic Envs
on: push

jobs:
  first:
    steps:
      - name: Set environment variable
        run: |
          echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "COMMIT_SHORT=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Use environment variables
        run: |
          echo "Build date: $BUILD_DATE"
          echo "Short commit: $COMMIT_SHORT"
