name: first_workflow
on: workflow_dispatch

jobs:
  "first_workflow":
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello"

  "second_flow":
    runs-on: ubuntu-latest
    needs: first_workflow
    steps:
      - name: say Tushal
        run: echo "Tushal"
      - name: make folder dist
        run : mkdir -p dist
      - name: say arjun
        run: echo "arjun"> dist/arjun.txt
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: artifact_second_flow
          path: dist
          retention-days: 3
